// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto

package example

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddCategoryRequest struct {
	Category             *Category `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddCategoryRequest) Reset()         { *m = AddCategoryRequest{} }
func (m *AddCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*AddCategoryRequest) ProtoMessage()    {}
func (*AddCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{0}
}

func (m *AddCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCategoryRequest.Unmarshal(m, b)
}
func (m *AddCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCategoryRequest.Marshal(b, m, deterministic)
}
func (m *AddCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCategoryRequest.Merge(m, src)
}
func (m *AddCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_AddCategoryRequest.Size(m)
}
func (m *AddCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddCategoryRequest proto.InternalMessageInfo

func (m *AddCategoryRequest) GetCategory() *Category {
	if m != nil {
		return m.Category
	}
	return nil
}

type AddCategoryResponse struct {
	Category             *Category `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddCategoryResponse) Reset()         { *m = AddCategoryResponse{} }
func (m *AddCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*AddCategoryResponse) ProtoMessage()    {}
func (*AddCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{1}
}

func (m *AddCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCategoryResponse.Unmarshal(m, b)
}
func (m *AddCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCategoryResponse.Marshal(b, m, deterministic)
}
func (m *AddCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCategoryResponse.Merge(m, src)
}
func (m *AddCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_AddCategoryResponse.Size(m)
}
func (m *AddCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddCategoryResponse proto.InternalMessageInfo

func (m *AddCategoryResponse) GetCategory() *Category {
	if m != nil {
		return m.Category
	}
	return nil
}

type ListCategoryRequest struct {
	Categories           []*Category `protobuf:"bytes,2,rep,name=categories,proto3" json:"categories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListCategoryRequest) Reset()         { *m = ListCategoryRequest{} }
func (m *ListCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*ListCategoryRequest) ProtoMessage()    {}
func (*ListCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{2}
}

func (m *ListCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCategoryRequest.Unmarshal(m, b)
}
func (m *ListCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCategoryRequest.Marshal(b, m, deterministic)
}
func (m *ListCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCategoryRequest.Merge(m, src)
}
func (m *ListCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_ListCategoryRequest.Size(m)
}
func (m *ListCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCategoryRequest proto.InternalMessageInfo

func (m *ListCategoryRequest) GetCategories() []*Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

type ListCategoryResponse struct {
	Categories           []*Category `protobuf:"bytes,2,rep,name=categories,proto3" json:"categories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListCategoryResponse) Reset()         { *m = ListCategoryResponse{} }
func (m *ListCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*ListCategoryResponse) ProtoMessage()    {}
func (*ListCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{3}
}

func (m *ListCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCategoryResponse.Unmarshal(m, b)
}
func (m *ListCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCategoryResponse.Marshal(b, m, deterministic)
}
func (m *ListCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCategoryResponse.Merge(m, src)
}
func (m *ListCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_ListCategoryResponse.Size(m)
}
func (m *ListCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCategoryResponse proto.InternalMessageInfo

func (m *ListCategoryResponse) GetCategories() []*Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

type Category struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price                int32    `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	ExternalId           string   `protobuf:"bytes,4,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{4}
}

func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (m *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(m, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Category) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Category) GetExternalId() string {
	if m != nil {
		return m.ExternalId
	}
	return ""
}

func init() {
	proto.RegisterType((*AddCategoryRequest)(nil), "example.AddCategoryRequest")
	proto.RegisterType((*AddCategoryResponse)(nil), "example.AddCategoryResponse")
	proto.RegisterType((*ListCategoryRequest)(nil), "example.ListCategoryRequest")
	proto.RegisterType((*ListCategoryResponse)(nil), "example.ListCategoryResponse")
	proto.RegisterType((*Category)(nil), "example.Category")
}

func init() { proto.RegisterFile("example.proto", fileDescriptor_15a1dc8d40dadaa6) }

var fileDescriptor_15a1dc8d40dadaa6 = []byte{
	// 391 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x4f, 0x8f, 0xd2, 0x40,
	0x1c, 0x4d, 0x0b, 0x08, 0xfe, 0x1a, 0x31, 0x0c, 0x24, 0x36, 0x15, 0x23, 0xe9, 0x89, 0x18, 0xdb,
	0x0a, 0x26, 0x1e, 0xf4, 0x04, 0x78, 0x90, 0xc4, 0x13, 0xc6, 0x8b, 0x17, 0x33, 0x74, 0x7e, 0xd4,
	0x09, 0x6d, 0xa7, 0x76, 0x06, 0x05, 0x8f, 0x7e, 0x84, 0xdd, 0x8f, 0xb6, 0xc7, 0xbd, 0xee, 0x07,
	0xd9, 0xec, 0x50, 0xfe, 0xb3, 0x87, 0xdd, 0x53, 0xfb, 0xde, 0xbc, 0x79, 0xef, 0xfd, 0x66, 0x06,
	0x9e, 0xe1, 0x92, 0x26, 0x59, 0x8c, 0x7e, 0x96, 0x0b, 0x25, 0x48, 0xb5, 0x80, 0x4e, 0x3b, 0x12,
	0x22, 0x8a, 0x31, 0xa0, 0x19, 0x0f, 0x68, 0x9a, 0x0a, 0x45, 0x15, 0x17, 0xa9, 0x5c, 0xcb, 0x9c,
	0xb7, 0xfa, 0x13, 0x7a, 0x11, 0xa6, 0x9e, 0xfc, 0x4b, 0xa3, 0x08, 0xf3, 0x40, 0x64, 0x5a, 0x71,
	0xaa, 0x76, 0x47, 0x40, 0x06, 0x8c, 0x8d, 0xa8, 0xc2, 0x48, 0xe4, 0xab, 0x09, 0xfe, 0x5e, 0xa0,
	0x54, 0xc4, 0x83, 0x5a, 0x58, 0x50, 0xb6, 0xd1, 0x31, 0xba, 0x56, 0xbf, 0xe1, 0x6f, 0xca, 0x6c,
	0xb5, 0x5b, 0x89, 0xfb, 0x19, 0x9a, 0x07, 0x26, 0x32, 0x13, 0xa9, 0xc4, 0x87, 0xba, 0x7c, 0x81,
	0xe6, 0x57, 0x2e, 0xd5, 0x71, 0x97, 0x1e, 0x40, 0x21, 0xe1, 0x28, 0x6d, 0xb3, 0x53, 0x3a, 0xef,
	0xb3, 0x27, 0x72, 0xc7, 0xd0, 0x3a, 0x74, 0x2a, 0x0a, 0x3d, 0xc2, 0x0a, 0xa1, 0xb6, 0xe1, 0x49,
	0x1d, 0x4c, 0xce, 0xf4, 0x24, 0x4f, 0x27, 0x26, 0x67, 0x84, 0x40, 0x39, 0xa5, 0x09, 0xda, 0xa6,
	0x66, 0xf4, 0x3f, 0x69, 0x41, 0x25, 0xcb, 0x79, 0x88, 0x76, 0xa9, 0x63, 0x74, 0x2b, 0x93, 0x35,
	0x20, 0xaf, 0xc1, 0xc2, 0xa5, 0xc2, 0x3c, 0xa5, 0xf1, 0x4f, 0xce, 0xec, 0xb2, 0xde, 0x00, 0x1b,
	0x6a, 0xcc, 0xfa, 0xd7, 0x06, 0x58, 0xdf, 0x25, 0xe6, 0xdf, 0x30, 0xff, 0x73, 0xb7, 0x81, 0x81,
	0xb5, 0x77, 0xa2, 0xe4, 0xe5, 0xb6, 0xe4, 0xe9, 0x65, 0x39, 0xed, 0xf3, 0x8b, 0xeb, 0x99, 0x5d,
	0xe7, 0xff, 0xd5, 0xcd, 0xa5, 0xd9, 0x72, 0x9f, 0xeb, 0xe7, 0xb2, 0x9b, 0xec, 0xa3, 0xf1, 0x86,
	0xcc, 0xa0, 0xbe, 0x77, 0x4e, 0x1c, 0x25, 0xd9, 0x79, 0x9d, 0xb9, 0x0a, 0xe7, 0xd5, 0x3d, 0xab,
	0x45, 0xd4, 0x0b, 0x1d, 0xd5, 0x20, 0xc7, 0x51, 0xc3, 0xe1, 0xc5, 0xa0, 0x4a, 0x2a, 0xfd, 0x52,
	0xcf, 0x7f, 0xf7, 0xe3, 0x43, 0xc4, 0xd5, 0xaf, 0xc5, 0xd4, 0x0f, 0x45, 0x12, 0x64, 0x43, 0x1e,
	0xfe, 0x5b, 0xc9, 0xb9, 0x08, 0x66, 0x1c, 0x63, 0xe6, 0x25, 0x54, 0xce, 0xa5, 0x57, 0x64, 0x04,
	0xfa, 0x81, 0x7e, 0x2a, 0xd0, 0xf4, 0x89, 0x86, 0xef, 0x6f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x8a,
	0x15, 0x47, 0xf3, 0x15, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	AddCategory(ctx context.Context, in *AddCategoryRequest, opts ...grpc.CallOption) (*AddCategoryResponse, error)
	ListCategories(ctx context.Context, in *ListCategoryRequest, opts ...grpc.CallOption) (*ListCategoryResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) AddCategory(ctx context.Context, in *AddCategoryRequest, opts ...grpc.CallOption) (*AddCategoryResponse, error) {
	out := new(AddCategoryResponse)
	err := c.cc.Invoke(ctx, "/example.UserService/AddCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListCategories(ctx context.Context, in *ListCategoryRequest, opts ...grpc.CallOption) (*ListCategoryResponse, error) {
	out := new(ListCategoryResponse)
	err := c.cc.Invoke(ctx, "/example.UserService/ListCategories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	AddCategory(context.Context, *AddCategoryRequest) (*AddCategoryResponse, error)
	ListCategories(context.Context, *ListCategoryRequest) (*ListCategoryResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) AddCategory(ctx context.Context, req *AddCategoryRequest) (*AddCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCategory not implemented")
}
func (*UnimplementedUserServiceServer) ListCategories(ctx context.Context, req *ListCategoryRequest) (*ListCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCategories not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_AddCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AddCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.UserService/AddCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AddCategory(ctx, req.(*AddCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.UserService/ListCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListCategories(ctx, req.(*ListCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "example.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddCategory",
			Handler:    _UserService_AddCategory_Handler,
		},
		{
			MethodName: "ListCategories",
			Handler:    _UserService_ListCategories_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example.proto",
}
