// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto

package example

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	field_mask "google.golang.org/genproto/protobuf/field_mask"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Category struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price                int32                `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	ExternalId           string               `protobuf:"bytes,4,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	AdditionalPriceRule  *AdditionalPriceRule `protobuf:"bytes,5,opt,name=additional_price_rule,json=additionalPriceRule,proto3" json:"additional_price_rule,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{0}
}

func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (m *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(m, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Category) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Category) GetExternalId() string {
	if m != nil {
		return m.ExternalId
	}
	return ""
}

func (m *Category) GetAdditionalPriceRule() *AdditionalPriceRule {
	if m != nil {
		return m.AdditionalPriceRule
	}
	return nil
}

type AdditionalPriceRule struct {
	Condition            string   `protobuf:"bytes,1,opt,name=condition,proto3" json:"condition,omitempty"`
	Price                int32    `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdditionalPriceRule) Reset()         { *m = AdditionalPriceRule{} }
func (m *AdditionalPriceRule) String() string { return proto.CompactTextString(m) }
func (*AdditionalPriceRule) ProtoMessage()    {}
func (*AdditionalPriceRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{1}
}

func (m *AdditionalPriceRule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdditionalPriceRule.Unmarshal(m, b)
}
func (m *AdditionalPriceRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdditionalPriceRule.Marshal(b, m, deterministic)
}
func (m *AdditionalPriceRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdditionalPriceRule.Merge(m, src)
}
func (m *AdditionalPriceRule) XXX_Size() int {
	return xxx_messageInfo_AdditionalPriceRule.Size(m)
}
func (m *AdditionalPriceRule) XXX_DiscardUnknown() {
	xxx_messageInfo_AdditionalPriceRule.DiscardUnknown(m)
}

var xxx_messageInfo_AdditionalPriceRule proto.InternalMessageInfo

func (m *AdditionalPriceRule) GetCondition() string {
	if m != nil {
		return m.Condition
	}
	return ""
}

func (m *AdditionalPriceRule) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

type AddCategoryRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price                int32    `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	ExternalId           string   `protobuf:"bytes,4,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddCategoryRequest) Reset()         { *m = AddCategoryRequest{} }
func (m *AddCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*AddCategoryRequest) ProtoMessage()    {}
func (*AddCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{2}
}

func (m *AddCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCategoryRequest.Unmarshal(m, b)
}
func (m *AddCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCategoryRequest.Marshal(b, m, deterministic)
}
func (m *AddCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCategoryRequest.Merge(m, src)
}
func (m *AddCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_AddCategoryRequest.Size(m)
}
func (m *AddCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddCategoryRequest proto.InternalMessageInfo

func (m *AddCategoryRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AddCategoryRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddCategoryRequest) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *AddCategoryRequest) GetExternalId() string {
	if m != nil {
		return m.ExternalId
	}
	return ""
}

type AddCategoryResponse struct {
	Category             *Category `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddCategoryResponse) Reset()         { *m = AddCategoryResponse{} }
func (m *AddCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*AddCategoryResponse) ProtoMessage()    {}
func (*AddCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{3}
}

func (m *AddCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCategoryResponse.Unmarshal(m, b)
}
func (m *AddCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCategoryResponse.Marshal(b, m, deterministic)
}
func (m *AddCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCategoryResponse.Merge(m, src)
}
func (m *AddCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_AddCategoryResponse.Size(m)
}
func (m *AddCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddCategoryResponse proto.InternalMessageInfo

func (m *AddCategoryResponse) GetCategory() *Category {
	if m != nil {
		return m.Category
	}
	return nil
}

type ListCategoryRequest struct {
	Categories           []*Category `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListCategoryRequest) Reset()         { *m = ListCategoryRequest{} }
func (m *ListCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*ListCategoryRequest) ProtoMessage()    {}
func (*ListCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{4}
}

func (m *ListCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCategoryRequest.Unmarshal(m, b)
}
func (m *ListCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCategoryRequest.Marshal(b, m, deterministic)
}
func (m *ListCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCategoryRequest.Merge(m, src)
}
func (m *ListCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_ListCategoryRequest.Size(m)
}
func (m *ListCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCategoryRequest proto.InternalMessageInfo

func (m *ListCategoryRequest) GetCategories() []*Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

type ListCategoryResponse struct {
	Categories           []*Category `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListCategoryResponse) Reset()         { *m = ListCategoryResponse{} }
func (m *ListCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*ListCategoryResponse) ProtoMessage()    {}
func (*ListCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{5}
}

func (m *ListCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCategoryResponse.Unmarshal(m, b)
}
func (m *ListCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCategoryResponse.Marshal(b, m, deterministic)
}
func (m *ListCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCategoryResponse.Merge(m, src)
}
func (m *ListCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_ListCategoryResponse.Size(m)
}
func (m *ListCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCategoryResponse proto.InternalMessageInfo

func (m *ListCategoryResponse) GetCategories() []*Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

type UpdateCategoryRequest struct {
	Id                   string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 *wrappers.StringValue `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price                *wrappers.Int32Value  `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	ExternalId           *wrappers.StringValue `protobuf:"bytes,4,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	AdditionalPriceRule  *AdditionalPriceRule  `protobuf:"bytes,5,opt,name=additional_price_rule,json=additionalPriceRule,proto3" json:"additional_price_rule,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateCategoryRequest) Reset()         { *m = UpdateCategoryRequest{} }
func (m *UpdateCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCategoryRequest) ProtoMessage()    {}
func (*UpdateCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{6}
}

func (m *UpdateCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCategoryRequest.Unmarshal(m, b)
}
func (m *UpdateCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCategoryRequest.Marshal(b, m, deterministic)
}
func (m *UpdateCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCategoryRequest.Merge(m, src)
}
func (m *UpdateCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCategoryRequest.Size(m)
}
func (m *UpdateCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCategoryRequest proto.InternalMessageInfo

func (m *UpdateCategoryRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateCategoryRequest) GetName() *wrappers.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *UpdateCategoryRequest) GetPrice() *wrappers.Int32Value {
	if m != nil {
		return m.Price
	}
	return nil
}

func (m *UpdateCategoryRequest) GetExternalId() *wrappers.StringValue {
	if m != nil {
		return m.ExternalId
	}
	return nil
}

func (m *UpdateCategoryRequest) GetAdditionalPriceRule() *AdditionalPriceRule {
	if m != nil {
		return m.AdditionalPriceRule
	}
	return nil
}

type UpdateCategoryResponse struct {
	Category             *Category `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateCategoryResponse) Reset()         { *m = UpdateCategoryResponse{} }
func (m *UpdateCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateCategoryResponse) ProtoMessage()    {}
func (*UpdateCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{7}
}

func (m *UpdateCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCategoryResponse.Unmarshal(m, b)
}
func (m *UpdateCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCategoryResponse.Marshal(b, m, deterministic)
}
func (m *UpdateCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCategoryResponse.Merge(m, src)
}
func (m *UpdateCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateCategoryResponse.Size(m)
}
func (m *UpdateCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCategoryResponse proto.InternalMessageInfo

func (m *UpdateCategoryResponse) GetCategory() *Category {
	if m != nil {
		return m.Category
	}
	return nil
}

type UpdateCategoryV2Request struct {
	Category             *Category             `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	UpdateMask           *field_mask.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateCategoryV2Request) Reset()         { *m = UpdateCategoryV2Request{} }
func (m *UpdateCategoryV2Request) String() string { return proto.CompactTextString(m) }
func (*UpdateCategoryV2Request) ProtoMessage()    {}
func (*UpdateCategoryV2Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{8}
}

func (m *UpdateCategoryV2Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCategoryV2Request.Unmarshal(m, b)
}
func (m *UpdateCategoryV2Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCategoryV2Request.Marshal(b, m, deterministic)
}
func (m *UpdateCategoryV2Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCategoryV2Request.Merge(m, src)
}
func (m *UpdateCategoryV2Request) XXX_Size() int {
	return xxx_messageInfo_UpdateCategoryV2Request.Size(m)
}
func (m *UpdateCategoryV2Request) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCategoryV2Request.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCategoryV2Request proto.InternalMessageInfo

func (m *UpdateCategoryV2Request) GetCategory() *Category {
	if m != nil {
		return m.Category
	}
	return nil
}

func (m *UpdateCategoryV2Request) GetUpdateMask() *field_mask.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

type UpdateCategoryV2Response struct {
	Category             *Category `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateCategoryV2Response) Reset()         { *m = UpdateCategoryV2Response{} }
func (m *UpdateCategoryV2Response) String() string { return proto.CompactTextString(m) }
func (*UpdateCategoryV2Response) ProtoMessage()    {}
func (*UpdateCategoryV2Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{9}
}

func (m *UpdateCategoryV2Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCategoryV2Response.Unmarshal(m, b)
}
func (m *UpdateCategoryV2Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCategoryV2Response.Marshal(b, m, deterministic)
}
func (m *UpdateCategoryV2Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCategoryV2Response.Merge(m, src)
}
func (m *UpdateCategoryV2Response) XXX_Size() int {
	return xxx_messageInfo_UpdateCategoryV2Response.Size(m)
}
func (m *UpdateCategoryV2Response) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCategoryV2Response.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCategoryV2Response proto.InternalMessageInfo

func (m *UpdateCategoryV2Response) GetCategory() *Category {
	if m != nil {
		return m.Category
	}
	return nil
}

func init() {
	proto.RegisterType((*Category)(nil), "example.Category")
	proto.RegisterType((*AdditionalPriceRule)(nil), "example.AdditionalPriceRule")
	proto.RegisterType((*AddCategoryRequest)(nil), "example.AddCategoryRequest")
	proto.RegisterType((*AddCategoryResponse)(nil), "example.AddCategoryResponse")
	proto.RegisterType((*ListCategoryRequest)(nil), "example.ListCategoryRequest")
	proto.RegisterType((*ListCategoryResponse)(nil), "example.ListCategoryResponse")
	proto.RegisterType((*UpdateCategoryRequest)(nil), "example.UpdateCategoryRequest")
	proto.RegisterType((*UpdateCategoryResponse)(nil), "example.UpdateCategoryResponse")
	proto.RegisterType((*UpdateCategoryV2Request)(nil), "example.UpdateCategoryV2Request")
	proto.RegisterType((*UpdateCategoryV2Response)(nil), "example.UpdateCategoryV2Response")
}

func init() { proto.RegisterFile("example.proto", fileDescriptor_15a1dc8d40dadaa6) }

var fileDescriptor_15a1dc8d40dadaa6 = []byte{
	// 669 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xdf, 0x6e, 0xd3, 0x3e,
	0x14, 0x56, 0xda, 0xf5, 0xb7, 0xed, 0x54, 0xbf, 0x01, 0xde, 0xc6, 0xa2, 0xac, 0xdb, 0x42, 0x24,
	0xa4, 0x09, 0x68, 0xb2, 0x66, 0x12, 0x17, 0x4c, 0x5c, 0x6c, 0x20, 0xa0, 0x12, 0x48, 0x53, 0x27,
	0x76, 0xc1, 0x4d, 0xe5, 0x35, 0x5e, 0xb0, 0x96, 0xc6, 0x21, 0x4e, 0xf6, 0x07, 0xc4, 0x0d, 0x82,
	0x17, 0x80, 0x6b, 0x9e, 0x83, 0x07, 0xe1, 0x11, 0xe0, 0x41, 0x50, 0x6c, 0xa7, 0x4d, 0xdb, 0x8c,
	0x89, 0x4a, 0xbb, 0x6a, 0x7d, 0xce, 0xe7, 0xef, 0x3b, 0xfe, 0xce, 0xb1, 0x03, 0xff, 0x93, 0x73,
	0xdc, 0x8f, 0x02, 0x62, 0x47, 0x31, 0x4b, 0x18, 0x9a, 0x55, 0x4b, 0xa3, 0xe1, 0x33, 0xe6, 0x07,
	0xc4, 0xc1, 0x11, 0x75, 0x70, 0x18, 0xb2, 0x04, 0x27, 0x94, 0x85, 0x5c, 0xc2, 0x8c, 0x07, 0xe2,
	0xa7, 0xd7, 0xf4, 0x49, 0xd8, 0xe4, 0x67, 0xd8, 0xf7, 0x49, 0xec, 0xb0, 0x48, 0x20, 0x4a, 0xd0,
	0xeb, 0x8a, 0x4b, 0xac, 0x8e, 0xd2, 0x63, 0xe7, 0x2c, 0xc6, 0x51, 0x44, 0xe2, 0x3c, 0x6f, 0x8e,
	0xe7, 0x8f, 0x29, 0x09, 0xbc, 0x6e, 0x1f, 0xf3, 0x13, 0x89, 0xb0, 0x7e, 0x68, 0x30, 0xf7, 0x04,
	0x27, 0xc4, 0x67, 0xf1, 0x05, 0x5a, 0x80, 0x0a, 0xf5, 0x74, 0xcd, 0xd4, 0x36, 0xe7, 0x3b, 0x15,
	0xea, 0x21, 0x04, 0x33, 0x21, 0xee, 0x13, 0xbd, 0x22, 0x22, 0xe2, 0x3f, 0x5a, 0x82, 0x5a, 0x14,
	0xd3, 0x1e, 0xd1, 0xab, 0xa6, 0xb6, 0x59, 0xeb, 0xc8, 0x05, 0xda, 0x80, 0x3a, 0x39, 0x4f, 0x48,
	0x1c, 0xe2, 0xa0, 0x4b, 0x3d, 0x7d, 0x46, 0x6c, 0x80, 0x3c, 0xd4, 0xf6, 0xd0, 0x3e, 0x2c, 0x63,
	0xcf, 0xa3, 0x59, 0xf1, 0x38, 0xe8, 0x8a, 0x4d, 0xdd, 0x38, 0x0d, 0x88, 0x5e, 0x33, 0xb5, 0xcd,
	0xba, 0xdb, 0xb0, 0x73, 0xb7, 0x76, 0x07, 0xa8, 0xfd, 0x0c, 0xd4, 0x49, 0x03, 0xd2, 0x59, 0xc4,
	0x93, 0x41, 0xab, 0x0d, 0x8b, 0x25, 0x58, 0xd4, 0x80, 0xf9, 0x1e, 0x0b, 0x65, 0x5c, 0x1d, 0x65,
	0x18, 0x18, 0x56, 0x5f, 0x29, 0x54, 0x6f, 0x31, 0x40, 0xbb, 0x9e, 0x97, 0xdb, 0xd0, 0x21, 0xef,
	0x52, 0xc2, 0x93, 0x6b, 0x74, 0xc3, 0x7a, 0x2a, 0x6a, 0x1f, 0x0a, 0xf2, 0x88, 0x85, 0x9c, 0xa0,
	0x26, 0xcc, 0xf5, 0x54, 0x4c, 0xe8, 0xd6, 0xdd, 0x5b, 0x03, 0x5f, 0x06, 0xe0, 0x01, 0xc4, 0x7a,
	0x01, 0x8b, 0x2f, 0x29, 0x4f, 0xc6, 0xeb, 0x6e, 0x01, 0x28, 0x08, 0x25, 0x5c, 0xd7, 0xcc, 0x6a,
	0x39, 0x4f, 0x01, 0x64, 0xb5, 0x61, 0x69, 0x94, 0x49, 0x15, 0x34, 0x05, 0xd5, 0xf7, 0x0a, 0x2c,
	0xbf, 0x8e, 0x3c, 0x9c, 0x90, 0xab, 0xfc, 0xdc, 0x2a, 0xf8, 0x99, 0x4d, 0x80, 0x9c, 0x55, 0x3b,
	0x9f, 0x55, 0xfb, 0x20, 0x89, 0x69, 0xe8, 0x1f, 0xe2, 0x20, 0x25, 0xca, 0xed, 0x56, 0xd1, 0xed,
	0xba, 0xbb, 0x3a, 0xb1, 0xa5, 0x1d, 0x26, 0xdb, 0xae, 0xdc, 0xa1, 0x5a, 0xf1, 0x78, 0xb2, 0x15,
	0x57, 0x69, 0x5d, 0xef, 0xd8, 0x3e, 0x87, 0xdb, 0xe3, 0xf6, 0x4c, 0xd7, 0xfd, 0x2f, 0x1a, 0xac,
	0x8c, 0x32, 0x1d, 0xba, 0xb9, 0xd5, 0xff, 0x46, 0x85, 0x76, 0xa0, 0x9e, 0x0a, 0x26, 0xf1, 0x32,
	0xa8, 0x86, 0x18, 0x13, 0x26, 0x3d, 0xcb, 0x1e, 0x8f, 0x57, 0x98, 0x9f, 0x74, 0x40, 0xc2, 0xb3,
	0xff, 0x56, 0x1b, 0xf4, 0xc9, 0x32, 0xa6, 0x3a, 0x92, 0xfb, 0xab, 0x0a, 0x37, 0xf2, 0xf0, 0x01,
	0x89, 0x4f, 0xb3, 0x06, 0xfa, 0x50, 0x2f, 0x5c, 0x15, 0xb4, 0x5a, 0x74, 0x7c, 0x6c, 0xc2, 0x8c,
	0x46, 0x79, 0x52, 0x16, 0x63, 0xad, 0x7d, 0xfa, 0xf9, 0xfb, 0x5b, 0x65, 0xc5, 0x42, 0xe2, 0xe9,
	0x3d, 0x6d, 0x39, 0xc3, 0xa9, 0x7d, 0xa4, 0xdd, 0x43, 0x14, 0x16, 0x0a, 0x77, 0x80, 0x12, 0x8e,
	0x86, 0x74, 0x25, 0xd7, 0xcc, 0x58, 0xbb, 0x24, 0xab, 0xd4, 0x0c, 0xa1, 0xb6, 0x84, 0x4a, 0xd4,
	0x50, 0x0a, 0x0b, 0xa3, 0x96, 0xa1, 0xf5, 0x01, 0x59, 0xe9, 0xdd, 0x31, 0x36, 0x2e, 0xcd, 0x2b,
	0x39, 0x4b, 0xc8, 0x35, 0xdc, 0x95, 0x49, 0x39, 0xe7, 0x03, 0xf5, 0x3e, 0x66, 0x27, 0xfc, 0xac,
	0xc1, 0xcd, 0xf1, 0x56, 0x21, 0xf3, 0x12, 0xe6, 0xc1, 0x30, 0x19, 0x77, 0xfe, 0x82, 0x50, 0xea,
	0xf7, 0x85, 0xfa, 0x5d, 0xd7, 0x94, 0xea, 0xee, 0x88, 0x7a, 0xde, 0x5e, 0x5b, 0x96, 0xb1, 0xb7,
	0xf7, 0x75, 0x77, 0x16, 0xd5, 0xdc, 0x6a, 0xcb, 0xde, 0x7a, 0xf3, 0xd0, 0xa7, 0xc9, 0xdb, 0xf4,
	0xc8, 0xee, 0xb1, 0xbe, 0x13, 0xed, 0xd1, 0xde, 0xfb, 0x0b, 0x7e, 0xc2, 0xe4, 0x57, 0xaa, 0x99,
	0xcd, 0x22, 0x6f, 0x2a, 0x6d, 0xf9, 0x09, 0xdb, 0x51, 0xab, 0xa3, 0xff, 0xc4, 0x72, 0xfb, 0x4f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xf9, 0xeb, 0xd2, 0x58, 0x65, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CategoryServiceClient is the client API for CategoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CategoryServiceClient interface {
	AddCategory(ctx context.Context, in *AddCategoryRequest, opts ...grpc.CallOption) (*AddCategoryResponse, error)
	ListCategories(ctx context.Context, in *ListCategoryRequest, opts ...grpc.CallOption) (*ListCategoryResponse, error)
	UpdateCategory(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*UpdateCategoryResponse, error)
	UpdateCategoryV2(ctx context.Context, in *UpdateCategoryV2Request, opts ...grpc.CallOption) (*UpdateCategoryV2Response, error)
}

type categoryServiceClient struct {
	cc *grpc.ClientConn
}

func NewCategoryServiceClient(cc *grpc.ClientConn) CategoryServiceClient {
	return &categoryServiceClient{cc}
}

func (c *categoryServiceClient) AddCategory(ctx context.Context, in *AddCategoryRequest, opts ...grpc.CallOption) (*AddCategoryResponse, error) {
	out := new(AddCategoryResponse)
	err := c.cc.Invoke(ctx, "/example.CategoryService/AddCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryServiceClient) ListCategories(ctx context.Context, in *ListCategoryRequest, opts ...grpc.CallOption) (*ListCategoryResponse, error) {
	out := new(ListCategoryResponse)
	err := c.cc.Invoke(ctx, "/example.CategoryService/ListCategories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryServiceClient) UpdateCategory(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*UpdateCategoryResponse, error) {
	out := new(UpdateCategoryResponse)
	err := c.cc.Invoke(ctx, "/example.CategoryService/UpdateCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryServiceClient) UpdateCategoryV2(ctx context.Context, in *UpdateCategoryV2Request, opts ...grpc.CallOption) (*UpdateCategoryV2Response, error) {
	out := new(UpdateCategoryV2Response)
	err := c.cc.Invoke(ctx, "/example.CategoryService/UpdateCategoryV2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CategoryServiceServer is the server API for CategoryService service.
type CategoryServiceServer interface {
	AddCategory(context.Context, *AddCategoryRequest) (*AddCategoryResponse, error)
	ListCategories(context.Context, *ListCategoryRequest) (*ListCategoryResponse, error)
	UpdateCategory(context.Context, *UpdateCategoryRequest) (*UpdateCategoryResponse, error)
	UpdateCategoryV2(context.Context, *UpdateCategoryV2Request) (*UpdateCategoryV2Response, error)
}

// UnimplementedCategoryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCategoryServiceServer struct {
}

func (*UnimplementedCategoryServiceServer) AddCategory(ctx context.Context, req *AddCategoryRequest) (*AddCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCategory not implemented")
}
func (*UnimplementedCategoryServiceServer) ListCategories(ctx context.Context, req *ListCategoryRequest) (*ListCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCategories not implemented")
}
func (*UnimplementedCategoryServiceServer) UpdateCategory(ctx context.Context, req *UpdateCategoryRequest) (*UpdateCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCategory not implemented")
}
func (*UnimplementedCategoryServiceServer) UpdateCategoryV2(ctx context.Context, req *UpdateCategoryV2Request) (*UpdateCategoryV2Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCategoryV2 not implemented")
}

func RegisterCategoryServiceServer(s *grpc.Server, srv CategoryServiceServer) {
	s.RegisterService(&_CategoryService_serviceDesc, srv)
}

func _CategoryService_AddCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryServiceServer).AddCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.CategoryService/AddCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryServiceServer).AddCategory(ctx, req.(*AddCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryService_ListCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryServiceServer).ListCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.CategoryService/ListCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryServiceServer).ListCategories(ctx, req.(*ListCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryService_UpdateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryServiceServer).UpdateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.CategoryService/UpdateCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryServiceServer).UpdateCategory(ctx, req.(*UpdateCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryService_UpdateCategoryV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCategoryV2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryServiceServer).UpdateCategoryV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.CategoryService/UpdateCategoryV2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryServiceServer).UpdateCategoryV2(ctx, req.(*UpdateCategoryV2Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _CategoryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "example.CategoryService",
	HandlerType: (*CategoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddCategory",
			Handler:    _CategoryService_AddCategory_Handler,
		},
		{
			MethodName: "ListCategories",
			Handler:    _CategoryService_ListCategories_Handler,
		},
		{
			MethodName: "UpdateCategory",
			Handler:    _CategoryService_UpdateCategory_Handler,
		},
		{
			MethodName: "UpdateCategoryV2",
			Handler:    _CategoryService_UpdateCategoryV2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example.proto",
}
