// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto

package example

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Category struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price                int32    `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	ExternalId           string   `protobuf:"bytes,4,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{0}
}

func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (m *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(m, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Category) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Category) GetExternalId() string {
	if m != nil {
		return m.ExternalId
	}
	return ""
}

type AddCategoryRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price                int32    `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	ExternalId           string   `protobuf:"bytes,4,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddCategoryRequest) Reset()         { *m = AddCategoryRequest{} }
func (m *AddCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*AddCategoryRequest) ProtoMessage()    {}
func (*AddCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{1}
}

func (m *AddCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCategoryRequest.Unmarshal(m, b)
}
func (m *AddCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCategoryRequest.Marshal(b, m, deterministic)
}
func (m *AddCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCategoryRequest.Merge(m, src)
}
func (m *AddCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_AddCategoryRequest.Size(m)
}
func (m *AddCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddCategoryRequest proto.InternalMessageInfo

func (m *AddCategoryRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AddCategoryRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddCategoryRequest) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *AddCategoryRequest) GetExternalId() string {
	if m != nil {
		return m.ExternalId
	}
	return ""
}

type AddCategoryResponse struct {
	Category             *Category `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddCategoryResponse) Reset()         { *m = AddCategoryResponse{} }
func (m *AddCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*AddCategoryResponse) ProtoMessage()    {}
func (*AddCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{2}
}

func (m *AddCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCategoryResponse.Unmarshal(m, b)
}
func (m *AddCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCategoryResponse.Marshal(b, m, deterministic)
}
func (m *AddCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCategoryResponse.Merge(m, src)
}
func (m *AddCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_AddCategoryResponse.Size(m)
}
func (m *AddCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddCategoryResponse proto.InternalMessageInfo

func (m *AddCategoryResponse) GetCategory() *Category {
	if m != nil {
		return m.Category
	}
	return nil
}

type ListCategoryRequest struct {
	Categories           []*Category `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListCategoryRequest) Reset()         { *m = ListCategoryRequest{} }
func (m *ListCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*ListCategoryRequest) ProtoMessage()    {}
func (*ListCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{3}
}

func (m *ListCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCategoryRequest.Unmarshal(m, b)
}
func (m *ListCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCategoryRequest.Marshal(b, m, deterministic)
}
func (m *ListCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCategoryRequest.Merge(m, src)
}
func (m *ListCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_ListCategoryRequest.Size(m)
}
func (m *ListCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCategoryRequest proto.InternalMessageInfo

func (m *ListCategoryRequest) GetCategories() []*Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

type ListCategoryResponse struct {
	Categories           []*Category `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListCategoryResponse) Reset()         { *m = ListCategoryResponse{} }
func (m *ListCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*ListCategoryResponse) ProtoMessage()    {}
func (*ListCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{4}
}

func (m *ListCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCategoryResponse.Unmarshal(m, b)
}
func (m *ListCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCategoryResponse.Marshal(b, m, deterministic)
}
func (m *ListCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCategoryResponse.Merge(m, src)
}
func (m *ListCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_ListCategoryResponse.Size(m)
}
func (m *ListCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCategoryResponse proto.InternalMessageInfo

func (m *ListCategoryResponse) GetCategories() []*Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

func init() {
	proto.RegisterType((*Category)(nil), "example.Category")
	proto.RegisterType((*AddCategoryRequest)(nil), "example.AddCategoryRequest")
	proto.RegisterType((*AddCategoryResponse)(nil), "example.AddCategoryResponse")
	proto.RegisterType((*ListCategoryRequest)(nil), "example.ListCategoryRequest")
	proto.RegisterType((*ListCategoryResponse)(nil), "example.ListCategoryResponse")
}

func init() { proto.RegisterFile("example.proto", fileDescriptor_15a1dc8d40dadaa6) }

var fileDescriptor_15a1dc8d40dadaa6 = []byte{
	// 394 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x92, 0xcf, 0x6e, 0xda, 0x40,
	0x10, 0xc6, 0x65, 0x03, 0x85, 0x0e, 0x2a, 0x55, 0x17, 0xa4, 0x5a, 0x2e, 0xa8, 0xc8, 0x27, 0x54,
	0xd5, 0x76, 0xa1, 0x52, 0x0f, 0xed, 0x09, 0xda, 0x43, 0x91, 0x7a, 0xa2, 0xb7, 0x5e, 0xaa, 0xc5,
	0x9e, 0x6e, 0x57, 0xd8, 0x5e, 0xd7, 0xbb, 0x50, 0xc8, 0x31, 0x8f, 0x90, 0x3c, 0x5a, 0x5e, 0x21,
	0x79, 0x8f, 0x28, 0x8b, 0xcd, 0x9f, 0xe0, 0x1c, 0x72, 0xc8, 0xc9, 0x9e, 0x99, 0x6f, 0xbf, 0xdf,
	0xec, 0xa7, 0x85, 0x17, 0xb8, 0xa6, 0x71, 0x1a, 0xa1, 0x97, 0x66, 0x42, 0x09, 0x52, 0xcf, 0x4b,
	0xbb, 0xcb, 0x84, 0x60, 0x11, 0xfa, 0x34, 0xe5, 0x3e, 0x4d, 0x12, 0xa1, 0xa8, 0xe2, 0x22, 0x91,
	0x5b, 0x99, 0xfd, 0x5e, 0x7f, 0x02, 0x97, 0x61, 0xe2, 0xca, 0xff, 0x94, 0x31, 0xcc, 0x7c, 0x91,
	0x6a, 0xc5, 0xa9, 0xda, 0x41, 0x68, 0x7c, 0xa5, 0x0a, 0x99, 0xc8, 0x36, 0xa4, 0x05, 0x26, 0x0f,
	0x2d, 0xa3, 0x6f, 0x0c, 0x9e, 0xcf, 0x4c, 0x1e, 0x12, 0x02, 0xd5, 0x84, 0xc6, 0x68, 0x99, 0xba,
	0xa3, 0xff, 0x49, 0x07, 0x6a, 0x69, 0xc6, 0x03, 0xb4, 0x2a, 0x7d, 0x63, 0x50, 0x9b, 0x6d, 0x0b,
	0xf2, 0x16, 0x9a, 0xb8, 0x56, 0x98, 0x25, 0x34, 0xfa, 0xcd, 0x43, 0xab, 0xaa, 0x0f, 0x40, 0xd1,
	0x9a, 0x86, 0x8e, 0x00, 0x32, 0x0e, 0xc3, 0x82, 0x34, 0xc3, 0x7f, 0x4b, 0x94, 0xea, 0x29, 0x81,
	0xdf, 0xa0, 0x7d, 0x04, 0x94, 0xa9, 0x48, 0x24, 0x12, 0x17, 0x1a, 0x41, 0xde, 0xd3, 0xdc, 0xe6,
	0xe8, 0x95, 0x57, 0xa4, 0xbc, 0x13, 0xef, 0x24, 0xce, 0x77, 0x68, 0xff, 0xe0, 0x52, 0xdd, 0xdf,
	0x7b, 0x08, 0x90, 0x4b, 0x38, 0x4a, 0xcb, 0xe8, 0x57, 0xca, 0x7d, 0x0e, 0x44, 0xce, 0x14, 0x3a,
	0xc7, 0x4e, 0xf9, 0x42, 0x8f, 0xb7, 0x1a, 0xdd, 0x18, 0xf0, 0xb2, 0x18, 0xfc, 0xc4, 0x6c, 0x75,
	0x97, 0x07, 0x83, 0xe6, 0xc1, 0x75, 0xc9, 0x9b, 0x9d, 0xc3, 0x69, 0xea, 0x76, 0xb7, 0x7c, 0xb8,
	0x5d, 0xc8, 0xe9, 0x9d, 0x5f, 0x5d, 0x5f, 0x9a, 0xaf, 0x1d, 0xa2, 0x9f, 0xd7, 0x6a, 0xe8, 0xef,
	0xc9, 0x9f, 0x8d, 0x77, 0x84, 0x43, 0xeb, 0xe0, 0x1e, 0x1c, 0x25, 0xd9, 0xdb, 0x95, 0x44, 0x65,
	0xf7, 0x1e, 0x98, 0xe6, 0x34, 0x5b, 0xd3, 0x3a, 0xa4, 0x84, 0x36, 0x99, 0x5c, 0x8c, 0xeb, 0xa4,
	0x36, 0xaa, 0x0c, 0xbd, 0x0f, 0xbf, 0x3e, 0x31, 0xae, 0xfe, 0x2e, 0xe7, 0x5e, 0x20, 0x62, 0x3f,
	0x9d, 0xf0, 0xe0, 0x6c, 0x23, 0x17, 0xc2, 0xff, 0xc3, 0x31, 0x0a, 0xdd, 0x98, 0xca, 0x85, 0x74,
	0x73, 0x8c, 0xaf, 0x9f, 0xf5, 0x97, 0xbc, 0x9a, 0x3f, 0xd3, 0xe5, 0xc7, 0xdb, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x46, 0x91, 0xcd, 0xd2, 0x4b, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CategoryServiceClient is the client API for CategoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CategoryServiceClient interface {
	AddCategory(ctx context.Context, in *AddCategoryRequest, opts ...grpc.CallOption) (*AddCategoryResponse, error)
	ListCategories(ctx context.Context, in *ListCategoryRequest, opts ...grpc.CallOption) (*ListCategoryResponse, error)
}

type categoryServiceClient struct {
	cc *grpc.ClientConn
}

func NewCategoryServiceClient(cc *grpc.ClientConn) CategoryServiceClient {
	return &categoryServiceClient{cc}
}

func (c *categoryServiceClient) AddCategory(ctx context.Context, in *AddCategoryRequest, opts ...grpc.CallOption) (*AddCategoryResponse, error) {
	out := new(AddCategoryResponse)
	err := c.cc.Invoke(ctx, "/example.CategoryService/AddCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryServiceClient) ListCategories(ctx context.Context, in *ListCategoryRequest, opts ...grpc.CallOption) (*ListCategoryResponse, error) {
	out := new(ListCategoryResponse)
	err := c.cc.Invoke(ctx, "/example.CategoryService/ListCategories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CategoryServiceServer is the server API for CategoryService service.
type CategoryServiceServer interface {
	AddCategory(context.Context, *AddCategoryRequest) (*AddCategoryResponse, error)
	ListCategories(context.Context, *ListCategoryRequest) (*ListCategoryResponse, error)
}

// UnimplementedCategoryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCategoryServiceServer struct {
}

func (*UnimplementedCategoryServiceServer) AddCategory(ctx context.Context, req *AddCategoryRequest) (*AddCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCategory not implemented")
}
func (*UnimplementedCategoryServiceServer) ListCategories(ctx context.Context, req *ListCategoryRequest) (*ListCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCategories not implemented")
}

func RegisterCategoryServiceServer(s *grpc.Server, srv CategoryServiceServer) {
	s.RegisterService(&_CategoryService_serviceDesc, srv)
}

func _CategoryService_AddCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryServiceServer).AddCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.CategoryService/AddCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryServiceServer).AddCategory(ctx, req.(*AddCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryService_ListCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryServiceServer).ListCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.CategoryService/ListCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryServiceServer).ListCategories(ctx, req.(*ListCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CategoryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "example.CategoryService",
	HandlerType: (*CategoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddCategory",
			Handler:    _CategoryService_AddCategory_Handler,
		},
		{
			MethodName: "ListCategories",
			Handler:    _CategoryService_ListCategories_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example.proto",
}
